# Generated by Django 4.1.4 on 2022-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0002_blogmodel_delete_samplemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
            ],
        ),
    ]
